version: "3.8"

services:
  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb
    # environment:
    # INFLUXDB_DB: mydb
    # INFLUXDB_ADMIN_USER: admin
    # INFLUXDB_ADMIN_PASSWORD: admin_password
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    # environment:
    # GF_SECURITY_ADMIN_USER: admin
    # GF_SECURITY_ADMIN_PASSWORD: admin_password
    networks:
      - monitoring
    depends_on:
      - influxdb

volumes:
  influxdb_data:
  grafana_data:

networks:
  monitoring:
